name: MMO Server Release Publish

on:
  release:
    types:
      - prereleased
      - released

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Inventory Image
        working-directory: server
        run: |
          docker build . --tag ghcr.io/sijoma/godot-mmo-server:${{ github.event.release.tag_name }}
          docker push ghcr.io/sijoma/godot-mmo-server:${{ github.event.release.tag_name }}
